import {
  MapPin,
  Home,
  Briefcase,
  Utensils,
  GlassWater,
  Ticket,
  Building,
  Navigation,
  Search,
  Layers,
  LocateFixed,
  Menu,
  X,
  Footprints,
  BusFront,
  Ship,
  TrainFront,
  Bike,
  Car,
  ChevronRight,
  ChevronLeft,
  Settings2,
  Lightbulb,
  Route,
  Clock,
  CalendarDays,
  Trash2,
  Edit3,
  PlusCircle,
  Save,
  Info
} from 'lucide-react';

export const Icons = {
  MapPin,
  Home,
  Work: Briefcase,
  Restaurant: Utensils,
  Bar: GlassWater,
  Venue: Ticket, // or Building
  Shop: Building, // Placeholder, could be ShoppingCart
  Park: MapPin, // Placeholder, could be Trees
  Directions: Navigation, // or Route
  Search,
  MapStyle: Layers,
  Geolocate: LocateFixed,
  Menu,
  Close: X,
  Walking: Footprints,
  Bus: BusFront,
  Ferry: Ship,
  Train: TrainFront,
  Cycling: Bike,
  Driving: Car,
  Next: ChevronRight,
  Previous: ChevronLeft,
  Settings: Settings2,
  Suggestion: Lightbulb,
  Route,
  Time: Clock,
  Day: CalendarDays,
  Delete: Trash2,
  Edit: Edit3,
  Add: PlusCircle,
  Save,
  Info,
};

export type IconName = keyof typeof Icons;
